# Changes here will be overwritten by Copier; NEVER edit this file manually.
_commit: template/v1.32.0
_rubio_template_version: template/v1.30.2
_src_path: gh:Rubio-Enterprises/standards
archetype: bare
default_branch: main
is_fork: false
project_name: claude-lsps
tier: internal
uses_release_please: false
